/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleaseNotesIndexRouteImport } from './routes/release-notes/index'
import { Route as ReleaseNotesV121RouteImport } from './routes/release-notes/v1-2-1'
import { Route as ReleaseNotesV120RouteImport } from './routes/release-notes/v1-2-0'
import { Route as ReleaseNotesV110RouteImport } from './routes/release-notes/v1-1-0'
import { Route as ReleaseNotesV100RouteImport } from './routes/release-notes/v1-0-0'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesIndexRoute = ReleaseNotesIndexRouteImport.update({
  id: '/release-notes/',
  path: '/release-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesV121Route = ReleaseNotesV121RouteImport.update({
  id: '/release-notes/v1-2-1',
  path: '/release-notes/v1-2-1',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesV120Route = ReleaseNotesV120RouteImport.update({
  id: '/release-notes/v1-2-0',
  path: '/release-notes/v1-2-0',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesV110Route = ReleaseNotesV110RouteImport.update({
  id: '/release-notes/v1-1-0',
  path: '/release-notes/v1-1-0',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseNotesV100Route = ReleaseNotesV100RouteImport.update({
  id: '/release-notes/v1-0-0',
  path: '/release-notes/v1-0-0',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/release-notes/v1-0-0': typeof ReleaseNotesV100Route
  '/release-notes/v1-1-0': typeof ReleaseNotesV110Route
  '/release-notes/v1-2-0': typeof ReleaseNotesV120Route
  '/release-notes/v1-2-1': typeof ReleaseNotesV121Route
  '/release-notes/': typeof ReleaseNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/release-notes/v1-0-0': typeof ReleaseNotesV100Route
  '/release-notes/v1-1-0': typeof ReleaseNotesV110Route
  '/release-notes/v1-2-0': typeof ReleaseNotesV120Route
  '/release-notes/v1-2-1': typeof ReleaseNotesV121Route
  '/release-notes': typeof ReleaseNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/release-notes/v1-0-0': typeof ReleaseNotesV100Route
  '/release-notes/v1-1-0': typeof ReleaseNotesV110Route
  '/release-notes/v1-2-0': typeof ReleaseNotesV120Route
  '/release-notes/v1-2-1': typeof ReleaseNotesV121Route
  '/release-notes/': typeof ReleaseNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/dashboard'
    | '/release-notes/v1-0-0'
    | '/release-notes/v1-1-0'
    | '/release-notes/v1-2-0'
    | '/release-notes/v1-2-1'
    | '/release-notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/dashboard'
    | '/release-notes/v1-0-0'
    | '/release-notes/v1-1-0'
    | '/release-notes/v1-2-0'
    | '/release-notes/v1-2-1'
    | '/release-notes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/release-notes/v1-0-0'
    | '/release-notes/v1-1-0'
    | '/release-notes/v1-2-0'
    | '/release-notes/v1-2-1'
    | '/release-notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReleaseNotesV100Route: typeof ReleaseNotesV100Route
  ReleaseNotesV110Route: typeof ReleaseNotesV110Route
  ReleaseNotesV120Route: typeof ReleaseNotesV120Route
  ReleaseNotesV121Route: typeof ReleaseNotesV121Route
  ReleaseNotesIndexRoute: typeof ReleaseNotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes/': {
      id: '/release-notes/'
      path: '/release-notes'
      fullPath: '/release-notes/'
      preLoaderRoute: typeof ReleaseNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes/v1-2-1': {
      id: '/release-notes/v1-2-1'
      path: '/release-notes/v1-2-1'
      fullPath: '/release-notes/v1-2-1'
      preLoaderRoute: typeof ReleaseNotesV121RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes/v1-2-0': {
      id: '/release-notes/v1-2-0'
      path: '/release-notes/v1-2-0'
      fullPath: '/release-notes/v1-2-0'
      preLoaderRoute: typeof ReleaseNotesV120RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes/v1-1-0': {
      id: '/release-notes/v1-1-0'
      path: '/release-notes/v1-1-0'
      fullPath: '/release-notes/v1-1-0'
      preLoaderRoute: typeof ReleaseNotesV110RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release-notes/v1-0-0': {
      id: '/release-notes/v1-0-0'
      path: '/release-notes/v1-0-0'
      fullPath: '/release-notes/v1-0-0'
      preLoaderRoute: typeof ReleaseNotesV100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReleaseNotesV100Route: ReleaseNotesV100Route,
  ReleaseNotesV110Route: ReleaseNotesV110Route,
  ReleaseNotesV120Route: ReleaseNotesV120Route,
  ReleaseNotesV121Route: ReleaseNotesV121Route,
  ReleaseNotesIndexRoute: ReleaseNotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
